// API Configuration
// This file fetches the API URL from api-config.json (generated by CDK deployment)
// or uses localhost for local development
window.RIAM_CONFIG = {
    apiBaseUrl: null,
    endpoints: null,
    isLoading: true
};

// Promise that resolves when config is loaded - other scripts should await this
let configResolve;
window.RIAM_CONFIG_READY = new Promise((resolve) => {
    configResolve = resolve;
});

// Function to load API config
async function loadApiConfig() {
    // Check if running locally
    if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
        console.log('[Config] Running locally - using localhost:8000');
        window.RIAM_CONFIG.apiBaseUrl = 'http://localhost:8000';
        window.RIAM_CONFIG.endpoints = {
            aiCoach: '/ai-coach/analyze',
            aiCoachChat: '/ai-coach/chat',
            login: '/auth/login',
            me: '/auth/me'
        };
        window.RIAM_CONFIG.isLoading = false;
        configResolve();
        return;
    }

    // Running in AWS - fetch the config from CDK-generated file
    try {
        console.log('[Config] Fetching API config from /api-config.json');
        const response = await fetch('/api-config.json');
        
        if (!response.ok) {
            throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        
        const data = await response.json();
        window.RIAM_CONFIG.apiBaseUrl = data.apiBaseUrl;
        window.RIAM_CONFIG.endpoints = data.endpoints;
        console.log('[Config] API config loaded:', {
            apiBaseUrl: window.RIAM_CONFIG.apiBaseUrl,
            endpoints: Object.keys(window.RIAM_CONFIG.endpoints)
        });
        
    } catch (error) {
        console.error('[Config] Failed to load api-config.json:', error);
        // Fallback - should not happen if CDK deployed correctly
        console.warn('[Config] Using fallback configuration');
        window.RIAM_CONFIG.apiBaseUrl = window.location.origin.replace(':5000', ':8000');
        window.RIAM_CONFIG.endpoints = {
            aiCoach: '/ai-coach/analyze',
            aiCoachChat: '/ai-coach/chat',
            login: '/auth/login',
            me: '/auth/me'
        };
    }
    
    window.RIAM_CONFIG.isLoading = false;
    configResolve();
}

// Load config immediately
loadApiConfig();


